name: movie-recommendation

services:
  app:
    build:
      context: D:\курсач бд
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      - DB_HOST=db
      - DB_NAME=movie_recommendation_system
      - DB_USER=postgres
      - DB_PASSWORD=luntik2406
      - DB_PORT=5432
    volumes:
      - type: bind
        source: D:\курсач бд
        target: /app
        bind:
          create_host_path: true
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=movie_recommendation_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=luntik2406
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      - type: bind
        source: D:\курсач бд\init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        bind:
          create_host_path: true

volumes:
  pgdata: