@echo off
cd "D:\курсач бд"
echo Stopping existing containers...
docker-compose down
echo Starting database in background...
docker-compose up -d db
echo Starting application in interactive mode...
docker-compose run --rm app